# Generated by Django 5.2.7 on 2025-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_employee_remove_facelog_user_facelog_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_embedding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
